<!DOCTYPE html>
<html ng-app="BeerSquirrel">
<head>
<title>Beer Squirrel</title>
<meta name="viewport" content="initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" />
<link rel="shortcut icon" href="/icon.png">
<link rel="apple-touch-icon" href="/icon.png" />
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

<meta property="og:image" content="/icon.png">
<meta property="og:title" content="Beer Squirrel">
<meta property="og:url" content="http://beersquirrel.xyz">
<meta property="og:site_name" content="Beer Squirrel">


<link href="/octicons.css" rel="stylesheet" type="text/css">
<link href="/style.css" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Ruda:400,700,900" rel="stylesheet" type="text/css">

</head>
<body upload-paste>
<center>
<div class="content">
	<div class="logo">
		<h1>
			<a href="/"><span class="mega-octicon octicon-beer"></span>&nbsp;<span class="mega-octicon octicon-squirrel"></span></a>
			<span class="text">Beer Squirrel</span>
		</h1>
	</div>

	<div ng-view></div>

	<div class="footer">
		Rules: No porn or weird shit. Uploads are deleted every week.
	</div>
</div>
</center>

<script type="text/ng-template" id="home.html">
	<div class="home">
		<h2>Paste &amp; share images or text</h2>

		<div class="data" ng-class="{'error': error == 'large-file'}">
			<div class="instructions" ng-if="!error">
				<div ng-if="!isMobile">
					<p>Paste something from your clipboard using <b>Cmd+V</b></p>
				</div>
		
				<div ng-if="isMobile">
					<input type="file" class="file-upload" upload-field>
					<p><b>Tap</b> to upload an image</p>
				</div>
			</div>
			<div class="instructions" ng-if="error">
				<span ng-switch="error">
					<span ng-switch-when="large-file">File size too large</span>
					<span ng-switch-when="upload-error">Error uploading file</span>
					<span ng-switch-default></span>
				</span>
			</div>
		</div>
		
		<div class="text-input-wrap" ng-if="isMobile">
			<textarea class="text-input" placeholder="Paste here to upload text"></textarea>
		</div>

		<div class="tip">
			<span ng-switch="OS">
				<span ng-switch-when="mac">Pro tip: To copy a small screenshot in OSX, press <b>Shift+Ctrl+Cmd+4</b> and select the area you want to screenshot. Or press space and click the window you want.</span>
				<span ng-switch-when="win">Pro tip: To copy a window screenshot in Windows, press <b>Alt+PrtScn</b>.</span>
				<span ng-switch-default></span>
			</span>
		</div>
	</div>
</script>

<script type="text/ng-template" id="view.html">
	<div class="upload">

		<input type="text" class="upload-link" ng-model="url" id="upload-link">
	
		<div ng-if="file.type == 'image'">
			<img src="/file/{{file.uid}}" ng-if="file.uid" class="image">
		</div>

		<div ng-if="file.type == 'text'">
			<pre class="upload-content">{{file.content}}</pre>
		</div>
	</div>

</script>


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.17/angular.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.17/angular-route.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.17/angular-resource.js"></script>

<script type="text/javascript" src="/script.js"></script>
</body>
</html>