<!DOCTYPE html>
<html ng-app="Squirrelly">
<head>
<title>Squirrelly</title>
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" />

<link rel="shortcut icon" href="/icon.png">
<link rel="apple-touch-icon" href="/app.png" />
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

<meta property="og:image" content="/app.png">
<meta property="og:title" content="Squirrelly">
<meta property="og:url" content="http://squirrelly.io">
<meta property="og:site_name" content="Squirrelly">

<link href="/style.css" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Ruda:400,700,900" rel="stylesheet" type="text/css">

</head>
<body upload-paste>
<center>
<div class="content">
	<div class="nav">
		<a href="#" ng-click="back()" ng-if="showBack"><span class="octicon octicon-chevron-left back"></span></a>
	</div>
	<div class="logo">
		<h1>
			<a href="/"><div class="svg"></div></a>
			<span class="text">Beer Squirrel</span>
		</h1>
	</div>

	<div ng-view></div>

	<div class="footer home">
		<a href="https://github.com/arzynik/squirrelly">Squirrelly</a> is an open source project created by <a href="http://devin.la/" target="_blank">Devin Smith</a>, built with <a href="http://tipsy.la/" target="_blank">Tipsy</a>, with icons by <a href="https://octicons.github.com/" target="_blank">GitHub</a>
		&nbsp;No porn, illegal, or weird shit allowed. Uploads are deleted every week.
		<br><br>
	</div>
</div>
</center>

<script type="text/ng-template" id="home.html">
	<div class="home">
		<h2>Paste &amp; share images or text</h2>

		<div class="data" ng-class="{'error': error}">
			<div class="instructions" ng-if="!error">
				<div ng-if="!isMobile">
					<p>Paste something from your clipboard using <b>Cmd+V</b></p>
				</div>

				<div ng-if="isMobile">
					<p><b>Tap</b> to upload an image</p>
				</div>
			</div>
			<div class="instructions" ng-if="error">
				{{error}}
			</div>
			<div ng-if="isMobile">
				<input type="file" class="file-upload" upload-field>
			</div>
		</div>

		<div class="text-input-wrap" ng-if="isMobile">
			<textarea class="text-input" placeholder="Paste here to upload text"></textarea>
		</div>

		<div class="tip">
			<span ng-switch="OS">
				<span ng-switch-when="mac">Pro tip: To copy a small screenshot in OSX, press <b>Shift+Ctrl+Cmd+4</b> and select the area you want to screenshot. Or press space and click the window you want.</span>
				<span ng-switch-when="win">Pro tip: To copy a window screenshot in Windows, press <b>Alt+PrtScn</b>.</span>
				<span ng-switch-default></span>
			</span>
		</div>
	</div>
</script>

<script type="text/ng-template" id="view.html">
	<div class="upload">

		<input type="text" class="upload-link" ng-model="url" id="upload-link">

		<div ng-if="file.type == 'image' && file.uid">
			<a href="/file/{{file.uid}}" target="_self"><img ng-src="/file/{{file.uid}}" class="image"></a>
		</div>

		<div ng-if="file.type == 'text'">
			<pre class="upload-content">{{file.content}}</pre>
		</div>
	</div>

</script>


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-route.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-resource.js"></script>

<script type="text/javascript" src="/fastclick.js"></script>
<script type="text/javascript" src="/script.js"></script>
</body>
</html>
