<!DOCTYPE html>
<html ng-app="BeerSquirrel">
<head>
<title>Beer Squirrel</title>
<meta name="viewport" content="initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" />
<link rel="shortcut icon" href="/icon.png">

<meta property="og:image" content="/icon.png">
<meta property="og:title" content="Beer Squirrel">
<meta property="og:url" content="http://beersquirrel.xyz">
<meta property="og:site_name" content="Beer Squirrel">


<link href="/octicons.css" rel="stylesheet" type="text/css">
<link href="/style.css" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Ruda:400,700,900" rel="stylesheet" type="text/css">

</head>
<body upload-paste>
<center>
<div class="content">
	<div class="logo">
		<h1>
			<a href="/"><span class="mega-octicon octicon-beer"></span>&nbsp;<span class="mega-octicon octicon-squirrel"></span></a>
			<span class="text">Beer Squirrel</span>
		</h1>
	</div>

	<div ng-view></div>

	<div class="footer">
		Rules: No porn or weird shit please. Uploads are deleted every week.
	</div>
</div>
</center>

<script type="text/ng-template" id="home.html">
	<div class="home">
		<h2>Paste &amp; share images or text</h2>

		<div class="data">
			<p class="instructions">Paste something from your clipboard using <b>Cmd+V</b></p>
		</div>

		<div class="tip">
			Pro Tip: To copy a small screenshot in OSX, press <b>Shift+Ctrl+Cmd+4</b> and select the area you want to screenshot. Or press space and click the window you want.
		</div>
	</div>
</script>

<script type="text/ng-template" id="view.html">
	<div class="upload">
		<div ng-show="file.type == 'image'">
			<img src="/file/{{file.uid}}" ng-if="file.uid">
		</div>

		<div ng-show="file.type == 'text'">
			<pre class="upload-content">{{file.content}}</pre>
		</div>
	</div>

</script>


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.17/angular.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-beta.17/angular-route.js"></script>

<script type="text/javascript" src="/script.js"></script>
</body>
</html>